[server]
# 服务器配置 - Streamlit Cloud 兼容设置
headless = true
enableCORS = true
enableXsrfProtection = true
fileWatcherType = "none"

[browser]
# 浏览器配置
gatherUsageStats = false

[logger]
# 日志配置
level = "info"

[global]
# 全局配置
developmentMode = false

[client]
# 客户端配置
showErrorDetails = true  # 开启以便调试
toolbarMode = "auto"

[theme]
# 主题配置
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"